### ISSUE TITLE
Azure Data Factory generates UTF-8 blob with a BOM

### ISSUE THREAD

**Issue by fbdntm** [Azure/Azure-DataFactory#91] opened 2019-04-01 18:13 UTC
When using Data Factory V2 with an output Dataset being a Json on an Azure Storage Blob V2 with a blank encodingName, the blob is encoded in UTF-8 with a BOM at the beginning, which is not conventional for UTF-8 and is not consistent with the output of other Azure services.
For instance, when output binding an Azure Function to a blob and not specifying the encoding, it generates an UTF-8 blob without a BOM.

**Comment by jonarmstrong** [comment] 2020-09-01 21:56
I've run into this same problem. If a use a dataset with the following definition, then the json file that is written is in UTF8-BOM encoding, which makes it incompatible with data flows.

``` json
{
    "name": "Raw_Deals_json",
    "properties": {
        "description": "This is the full export of the Deals w/o any additional processing",
        "linkedServiceName": {
            "referenceName": "datawarehouse_int",
            "type": "LinkedServiceReference"
        },
        "folder": {
            "name": "DataLake"
        },
        "annotations": [],
        "type": "Json",
        "typeProperties": {
            "location": {
                "type": "AzureBlobFSLocation",
                "fileName": "deals.json",
                "folderPath": "staged",
                "fileSystem": "int"
            }
        }
    },
    "type": "Microsoft.DataFactory/factories/datasets"
}
```

**Comment by hmayer1980** [comment] 2020-12-16 10:22
I did run into the same issue.
You should be able to specifiy either both verson UTF-8 without BOM and UTF-8 with BOM or not writing a BOM as default at all...

**Comment by jenilChristo** [comment] 2021-01-20 19:39
Facing the same issue in ADF json blob dataset.Is there a workaround to get rid of the BOM , while writing json dataset to Blob?. I am using the default (utf-8) encoding.

**Comment by rahash123** [comment] 2021-02-02 11:41
I was facing the same issue. It got resolved when I set the Encoding to US-ASCII while defining the dataset.
![image](https://user-images.githubusercontent.com/43533271/106595458-9f1f2a00-6579-11eb-8004-0c8270c96ca3.png)

**Comment by jashwood** [comment] 2021-03-16 12:00
Actually, this is really not cool. This is a workaround.

**Comment by shawnxzq** [comment] 2021-03-17 00:12
This is a known issue and we have work item to track this, will update here once it's resolved.

For now, if you choose "SetOfObjects" pattern in copy sink, the generated json will be able to consume in spark and have better performance than using "ArrayOfObjects" pattern

**Comment by valfirst** [comment] 2021-04-19 11:28
@fhljys was this issue fixed?

**Comment by fhljys** [comment] 2021-04-20 01:57
I think the current status is that @shawnxzq provided a workaround.

**Comment by shawnxzq** [comment] 2021-05-18 13:02
@fbdntm As this is a known issue and we have work item to track this, are you OK to close the issue here? Thanks!

**Comment by hmayer1980** [comment] 2021-05-18 13:46
I think it would be better to keep it open and you actually update it when your Work item is done - and a solution available to us.

**Comment by rocque57** [comment] 2021-06-07 23:15
The workaround that was suggested did not work.  Whether you select SetOfObjects or ArrayOfObjects for your sink the resulting file still has a BOM.
{"StatusCode":"DFExecutorUserError","Message":"Job failed due to reason: at Source 'SinkJSON': org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, 10.139.64.11, executor 0): org.apache.spark.SparkException: **Malformed records are detected in schema inference.** Parse Mode: FAILFAST.\n\tat

**Comment by shawnxzq** [comment] 2021-06-09 12:14
@rocque57 You are right that json files with utf-8 encoding generated by copy will always have BOM, however, if you set pattern as "SetOfObjects" in copy sink, and set documetForm to "document per line" in dataflow source, you won't get the error mentioned above and this is also the recommended setting from perf perspective.

**Comment by shawnxzq** [comment] 2021-07-07 10:17
@rocque57 As discussed, we have backlog items to track this, no clear ETA at moment, thanks!

**Comment by shawnxzq** [comment] 2021-08-05 03:36
@rocque57 This is still in backlog as a new ask, thanks for your patience, thx!

**Comment by ma185360** [comment] 2021-08-09 14:18
@rocque57 Any Update on this??

**Comment by Evogelpohl** [comment] 2021-08-17 15:13
FWiW: Had the same error w/ Azure Data Factory reading a path full of jSON files written by PowerShell's approach, ala: 
`$res = Invoke-RestMethod ...
$res | ConvertTo-Json | Out-File .../some.json `

As per above, trying to open those json files in Azure Data Factory Data Flow (using any option of json reading, Document Per line or Array of documents (which it is)) produced the FASTFAIL Malformed BOM error.

To Out-File, I added `-Encoding utf8NoBOM`. Azure Data Factory now reads the json files as expected.

**Comment by shawnxzq** [comment] 2021-09-03 10:38
Latest update, this is included in our acting plan now, ETA to get the fix will be 1~2 months later, thanks!

**Comment by shawnxzq** [comment] 2021-09-23 12:08
Most work done, pending deployment now.

**Comment by LockTar** [comment] 2021-09-23 12:10
@shawnxzq what will be the end result? Must we update our datasets, pipelines etc? Or will the new default be without BOM?
Thanks

**Comment by mguard11** [comment] 2021-09-27 18:55
@shawnxzq is there a tentative deployment date ?

**Comment by Eniemela** [comment] 2021-09-30 07:35
Currently manually setting encoding "UTF-8 without BOM" did solve this issue for me

**Comment by shawnxzq** [comment] 2021-09-30 14:16
Thanks @Eniemela  for confirm, later we will have full UX support for this as well, it will come next month.

**Comment by mguard11** [comment] 2021-10-22 01:02
Hi @shawnxzq  is this being deployed next week with full UX support ?

Thanks
Danesh

**Comment by yew** [comment] 2021-11-09 05:37
@mguard11 did you used Azure IR or SHIR? If the latter, please make sure the version is above 5.10.7918.2. You can download the latest version [here](https://www.microsoft.com/en-us/download/details.aspx?id=39717).

**Comment by yew** [comment] 2021-11-09 05:42
@mguard11 , in our telemetry, I can see your SHIR version is 4.15.7611.1, please upgrade it to use the new feature.

**Comment by shawnxzq** [comment] 2021-11-25 10:03
Close it since issue is already fixed.

**Closed by shawnxzq** 2021-11-25 10:03 UTC

**Comment by Eniemela** [comment] 2021-11-26 09:02
This "fix" apparently breaks the functionality again in Synapse! Synapse UI now enables selecting UTF-8 without BOM  -but it fails to validate!

**Comment by yew** [comment] 2021-11-26 09:39
@Eniemela the feature is only supported in copy activity, @shawnxzq , is there a way to write a JSON file without BOM in dataflow?

**Comment by Eniemela** [comment] 2021-11-26 10:11
We use JSON dataset as Sink for Copy activity (-> stores JSON with BOM if Default(UTF-8) is selected) and use the same dataset as source in mapping data flow which breaks if Default(UTF-8) is selected since it expects no BOM. This worked for use when we could manually enter "UTF-8 without BOM" to dataset but broke again when this UI support came out since it now prevents to use this value with mapping data flow

**Comment by yew** [comment] 2021-11-29 05:27
@Eniemela , oh, I see. Please kindly create 2 datasets to avoid the issue: in copy sink, select "UTF-8 without BOM", and in dataflow source just use "Default" or select "UTF-8".

**Comment by chr0m** [comment] 2021-12-21 05:17
> 

No offence, but that is a ridiculous solution. My ADF is config driven from the database, I'm expected to create a whole new dataset just to use UTF-8 without BOM?

**Comment by chr0m** [comment] 2022-01-18 00:01
Is there a fix for this? It shouldn't be this hard to generate a UTF-8 CSV without BOM.
I'm using ADF Copy Data activity, I select "UTF-8 without BOM" from the encoding type dropdown and when I run I get an error saying that it isn't a valid encoding type. Ridiculous!

**Comment by yew** [comment] 2022-01-18 07:51
@chr0m "UTF-8 without BOM" is supported in ADF copy data activity. Are you using self hosted IR? If yes, please making sure its version is above 5.12.7976.1.

**Comment by chr0m** [comment] 2022-01-18 08:33
> @chr0m "UTF-8 without BOM" is supported in ADF copy data activity. Are you using self hosted IR? If yes, please making sure its version is above 5.12.7976.1.

I since discovered that it's the Get MetaData activity throwing the error when the dataset is set to UTF-8 without BOM

**Comment by yew** [comment] 2022-01-20 11:27
@chr0m Many thanks for your feedback, I can repro the error, we will fix it and update here.

**Comment by LockTar** [comment] 2022-01-20 12:17
> Please kindly create 2 datasets to avoid the issue: in copy sink, select "UTF-8 without BOM", and in dataflow source just use "Default" or select "UTF-8".

@yew is this going to be fixed? It's a bit strange that we must create 2 duplicate datasets... We work a lot with json datasets and there this is a real issue. 

Since this issue is closed. Will there be a new one, or will this one be opened again?

**Comment by bramvanhautte** [comment] 2022-09-08 10:52
@yew any update on this (closed) issue? Is there a new issue created?

I'm facing similar issues when using the copy activity with the 'UTF 8 without BOM' and trying to pick up that file in a Data Flow source using the same dataset.

It makes no sense to double up this dataset..
Thanks!

**Comment by zsponaugle** [comment] 2022-10-12 17:51
Hello @yew @shawnxzq @fhljys 

I think this should be re-opened as well. The dual-dataset work-around is not ideal. Like many above me, I am trying to use a Data Flow after a Copy Activity that contains a JSON sink dataset. At the time of this writing, using Azure IR, I tried various settings and here are their outcomes:

**one dataset using ISO-8859-1 encoding:**
Job failed due to reason: at Source 'source1': requirement failed: The lineSep option must be specified for the ISO-8859-1 encoding

**one dataset using US-ASCII encoding:**
Job failed due to reason: at Source 'source1': requirement failed: The lineSep option must be specified for the US-ASCII encoding

**Set of objects / Document per line and two datasets (UTF-8 without BOM, UTF-8 default):**
Job failed due to reason: at Source 'source1': Malformed records are detected in schema inference. Parse Mode: FAILFAST

**Set of objects / Document per line and one dataset (UTF-8 default):**
Job failed due to reason: at Source 'source1': Malformed records are detected in schema inference. Parse Mode: FAILFAST

**Array of objects / Array of documents and two datasets (UTF-8 without BOM, UTF-8 default) --> _WORKS_**

**Array of objects / Array of documents and one dataset (UTF-8 default):**
Job failed due to reason: at Source 'source1': Malformed records are detected in schema inference. Parse Mode: FAILFAST

So, as you can see, the only one that worked for me was using the two JSON datasets (copy activity sink set to _UTF-8 without BOM_ and Data Flow source one set to _Default(UTF-8)_ and setting copy sink file pattern to _Array of objects_ and setting Data Flow source options --> JSON settings --> Document Form: _Array of documents_

Thank you.

**Comment by Krumelur** [comment] 2022-11-26 10:36
Confirmed that @zsponaugle approach also worked here (note that it's meanwhile November 2022 and the issue still exists)

**Comment by SNY019** [comment] 2023-07-13 16:20
US-ASCII encoding work around works for me. (July 2023 Issue is very much alive)

**Comment by bt701** [comment] 2024-05-29 03:43
This is also pretty frustrating from dataflows. I suspect we have some older files that had this, some new that don't, so the dataflow just 'FAILSFAST', but doesn't even point you to the file or error message.

It's a little bit surprising that datafactory can't really process the files it creates by default

**Comment by niksolteq** [comment] 2024-08-07 13:10
> Confirmed that @zsponaugle approach also worked here (note that it's meanwhile November 2022 and the issue still exists)

Can you please explain this method more in depth?

I can see it is still an issue.

**Comment by imlps** [comment] 2026-01-28 07:53
I am facing this issue in 2026. Can't believe I am reading a 2019 post.... Setting UTF-8 without BOM at Sink during ingest stage, will end up with Data Flow error because the encoding is not supported... is there a real solution already?
