### ISSUE TITLE
SQL Syntax error generated in Copy activity when running the Pipeline

### ISSUE THREAD

**Issue by luisdvalle** [Azure/Azure-DataFactory#113] opened 2019-09-24 06:46 UTC
Hi DF team,

I'm using Data Factory to replicate an external MySQL database into an Azure Database MySQL in our internal environment which also triggers an Azure Function after a series of Copy Activities are completed.

The total number of Copy Activities I have is 15, all of them successfully complete but one. The Input and Output I get when executing this Copy Activity are:

Input:

`{
    "source": {
        "type": "AzureMySqlSource",
        "queryTimeout": "02:00:00"
    },
    "sink": {
        "type": "AzureMySqlSink",
        "writeBatchSize": 10000,
        "writeBatchTimeout": "00:00:30",
        "preCopyScript": "TRUNCATE TABLE stage_portal_users"
    },
    "enableStaging": false
}`

Output:

`{
    "dataRead": 169228,
    "dataWritten": 0,
    "sourcePeakConnections": 1,
    "sinkPeakConnections": 2,
    "rowsRead": 2846,
    "rowsCopied": 0,
    "copyDuration": 6,
    "throughput": 27.544,
    "errors": [
        {
            "Code": 11000,
            "Message": "'Type=MySql.Data.MySqlClient.MySqlException,Message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create,recent,expiry) values(1,1,'onboarding','one',timestamp('2017-10-06 10:02:' at line 1,Source=MySqlConnector,''Type=MySql.Data.MySqlClient.MySqlException,Message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create,recent,expiry) values(1,1,'onboarding','one',timestamp('2017-10-06 10:02:' at line 1,Source=mscorlib,'",
            "EventType": 0,
            "Category": 5,
            "Data": {},
            "MsgId": null,
            "ExceptionType": null,
            "Source": null,
            "StackTrace": null,
            "InnerEventInfos": []
        }
    ],
    "effectiveIntegrationRuntime": "DefaultIntegrationRuntime (Australia East)",
    "usedDataIntegrationUnits": 4,
    "usedParallelCopies": 1,
    "executionDetails": [
        {
            "source": {
                "type": "AzureMySql"
            },
            "sink": {
                "type": "AzureMySql"
            },
            "status": "Failed",
            "start": "2019-09-24T05:48:57.0780767Z",
            "duration": 6,
            "usedDataIntegrationUnits": 4,
            "usedParallelCopies": 1,
            "detailedDurations": {
                "queuingDuration": 3,
                "preCopyScriptDuration": 1,
                "timeToFirstByte": 0,
                "transferDuration": 2
            }
        }
    ]
}`

Error Details:

`{
    "errorCode": "2200",
    "message": "'Type=MySql.Data.MySqlClient.MySqlException,Message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create,recent,expiry) values(1,1,'onboarding','one',timestamp('2017-10-06 10:02:' at line 1,Source=MySqlConnector,''Type=MySql.Data.MySqlClient.MySqlException,Message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create,recent,expiry) values(1,1,'onboarding','one',timestamp('2017-10-06 10:02:' at line 1,Source=mscorlib,'",
    "failureType": "UserError",
    "target": "Copy_SimplePortalUsers"
}`

More background about this particular Copy Activity:

The Source Dataset has the following schema:

`CREATE TABLE my_table (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  member_id int(10) unsigned NOT NULL,
  status enum('onboarding','active','blocked') NOT NULL,
  factor enum('one','two') NOT NULL,
  create datetime NOT NULL,
  recent datetime NOT NULL,
  expiry datetime DEFAULT NULL,
  PRIMARY KEY (id),
  KEY my_table.fk.other_table (member_id),
  CONSTRAINT my_table.fk.other_table FOREIGN KEY (member_id) REFERENCES members (id)
) ENGINE=InnoDB AUTO_INCREMENT=2849 DEFAULT CHARSET=utf8;`

Destination Dataset:

`CREATE TABLE stage_my_table (
  id int(10) unsigned NOT NULL,
  member_id int(10) unsigned NOT NULL,
  status enum('onboarding','active','blocked') NOT NULL,
  factor enum('one','two') NOT NULL,
  create datetime NOT NULL,
  recent datetime NOT NULL,
  expiry datetime DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

In the Copy Activity definition:

Pre-copy script: `TRUNCATE TABLE stage_my_table`

-------------------

All my other Copy Activities and Datasets have the same setup and none of them fail except for this one. I have tried re-creating the Datasets and Copy activity and creating a separate pipeline but I can't get to fix this so I'm wondering if perhaps this is coming from the DataFactory end.

Thank you in advance for your help with this.

**Comment by luisdvalle** [comment] 2019-09-25 01:32
Another finding in this issue:

If in the copy activity that is failing, in 'source' I define a 'Query' instead of table and define the query like this:

`SELECT
id,
member_id,
status,
factor
from my_table`

and subsequently, in the 'mapping'for this copy activity, I map every column except for the last three columns **create**, **recent** and **expiry** (all of them with a `datetime` data type), the copy activity is successful.

Seems like DataFactory is failing to copy those `datetime` columns.

Interestingly, I have other tables in the DB with `datetime` columns that are not failing

**Comment by fhljys** [comment] 2021-03-22 14:20
Are you still experiencing this?

**Comment by fhljys** [comment] 2021-03-28 04:06
Close due to inactivity.

**Comment by luisdvalle** [comment] 2021-03-28 04:16
Hey @fhljys ,
Thanks for getting back to me. I'm no longer working for that company so not sure if they are still experience this issue 🤷🏼‍♂️. Thanks again.

**Comment by fhljys** [comment] 2021-03-28 04:19
Thank you @luisdvalle . I will close this issue now for time being, and we can reopen it anytime if someone else reported it again. Thanks.

**Comment by HosniAkremi** [comment] 2021-03-30 19:43
@fhljys I actually faced same kind of issue with a particular copy activity, whereas the rest of the cooy activities went fine.
Still not sure if this is being reproduced from ADF side.
Kindly do the needful to support on this.

**Comment by fhljys** [comment] 2021-03-31 01:13
@HosniAkremi , do you have an activity ID for the failed copy activity?

**Comment by fhljys** [comment] 2021-04-13 12:35
Close due to inactivity.

**Closed by fhljys** 2021-04-13 12:35 UTC

**Comment by sherifalaa55** [comment] 2022-08-18 10:29
In my case copy activity was failing because I had one of the columns named by a reserved keyword "order", I had to copy columns one by one until I found the column with the problem... I'm not sure if there is a work around to this
